"""empty message

Revision ID: 072549da90e2
Revises: 6e05a483a3d3
Create Date: 2019-04-25 16:20:21.085002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072549da90e2'
down_revision = '6e05a483a3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_event_organizer_id_user'), 'event', 'user', ['organizer_id'], ['id'])
    connection = op.get_bind()
    result = connection.execute("""
    UPDATE event SET organizer_id = 1 WHERE organizer_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_event_organizer_id_user'), 'event', type_='foreignkey')
    op.drop_column('event', 'organizer_id')
    # ### end Alembic commands ###
