"""empty message

Revision ID: 21006f281713
Revises: 072549da90e2
Create Date: 2019-04-25 16:27:52.763231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21006f281713'
down_revision = '072549da90e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'organizer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
